### ISSUE TITLE
Why is there no gh-pages branch

### ISSUE THREAD

**Issue by Haroenv** [bullgit/bullshit-job-titles#16]

**Comment by reimersjan** [comment]
the generator is just an "addon", the main part of this repo is the README.md ;)

**Comment by dervondenbergen** [comment]
maybe we could also display the job titles on an site.

if we just add every title also to a yaml file, which could be used by jekyll, then we could easily set up a list-page and also create an api :D 

you never know, when you need a bullshit job title in another application
