### ISSUE TITLE
add jobtitle.json

### ISSUE THREAD

**Issue by dervondenbergen** [bullgit/bullshit-job-titles#24]
If we add a bullshit job title json file, we could use them outside of http://bullg.it/bullshit-job-titles/.

An example is a @pebble app, where a random job title gets generated every time the app gets opened.

Is anyone against it or is everyone ok, If I add such a file.

Of course it has to be updated like the README.md and index.html file each time, when a new job title gets added.

**Comment by LukyVj** [comment]
That's an awesome idea, Felix. 
That's a huge +1 for meh

:+1: 

EDIT : 
And I'm not Lying <3 

![](http://puu.sh/jhNnk/8dfa4b7556.png)

**Comment by Haroenv** [comment]
Couldn't we then change the `index.html` file to reference that json file, would make it so only two have to be updated

**Comment by dervondenbergen** [comment]
Yes, totally :D

**Comment by Haroenv** [comment]
Update on this. I think we should do it and use a Jekyll/liquid `{% include titles.json%}`, makes it pretty clear. I'll whip it up later today (normally)
